labels:
  app.kubernetes.io/name: cbsonarr
  app.kubernetes.io/managed-by: Helm
  app.kubernetes.io/instance: cbsonarr-instance
  app.kubernetes.io/version: 0.0.0
  app.kubernetes.io/component: cbsonarr-component
  app.kubernetes.io/part-of: cbbase

container:
  repo: ghcr.io/hotio
  image: sonarr
  version: release
  pull: IfNotPresent


persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi
  storageClass: longhorn

storage:
  mountPoint: /config

network:
  externalPort: 8989
  internalPort: 8989
  proto: TCP
  type: LoadBalancer
