labels:
  app.kubernetes.io/name: cbradarr
  app.kubernetes.io/managed-by: Helm
  app.kubernetes.io/instance: cbradarr-instance
  app.kubernetes.io/version: 0.0.0
  app.kubernetes.io/component: cbradarr-component
  app.kubernetes.io/part-of: cbshell

container:
  repo: ghcr.io/hotio
  image: radarr
  version: release
  pull: IfNotPresent


persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi
  storageClass: longhorn

storage:
  mountPoint: /config

network:
  externalPort: 7878
  internalPort: 7878
  proto: TCP
  type: LoadBalancer