apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: cbradarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cbradarr
  template:
    metadata:
      app: cbradarr
  spec:
    containers:
      - name: {{ .Chart.Name }}
        image: ghcr.io/hotio/radarr:release
        ports:
          - containerPort: 7878