{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
 name: {{ .Chart.Name }}-pvc
 namespace: {{ .Release.Namespace }}
 labels:
    {{- range $key, $val := .Values.labels }}
    {{ $key }}: {{ $val | quote }}
    {{- end}}
spec:
 storageClassName: {{ .Values.persistence.storageClass }}
 volumeName: {{ .Chart.Name }}-pv
 accessModes:
   - {{ .Values.persistence.accessMode | quote }}
 resources:
   requests:
     storage: {{ .Values.persistence.size | quote }}
 {{- end }}  