apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: cbradarr
    {{- range $key, $val := .Values.labels }}
    {{ $key }}: {{ $val | quote }}
    {{- end}}

spec:
  ports:
    - port: 7878
      protocol: TCP
      targetPort: 7878
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
  status:
    LoadBalancer: {}
  type: LoadBalancer
