apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- range $key, $val := .Values.labels }}
    {{ $key }}: {{ $val | quote }}
    {{- end}}

spec:
  ports:
    - port: {{ .Values.network.externalPort }}
      protocol: TCP
      targetPort: {{ .Values.network.internalPort }}
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
  type: LoadBalancer
