apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "{{ .Values.dns.fqdn }}"
    external-dns.alpha.kubernetes.io/ttl: "{{ .Values.dns.ttl }}"
  labels:
    {{- range $key, $val := .Values.labels }}
    {{ $key }}: {{ $val | quote }}
    {{- end}}

spec:
  ports:
    - port: {{ .Values.network.externalPort }}
      protocol: {{ .Values.network.proto }}
      targetPort: {{ .Values.network.internalPort }}
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
  type: {{ .Values.network.type }}
