apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cbshell
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/travismontana/cbhelm.git
    targetRevision: HEAD
    path: cbshell-chart
  destination:
    server: https://kubernetes.default.svc
    namespace: default
