persistence:
  storageClass: "longhorn"
  existingClaim: "home-pvc"
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi
  # if you need any additional volumes, you can define them here
  additionalVolumes: []
  # if you need any additional volume mounts, you can define them here
  additionalMounts: []

labels:
  app.kubernetes.io/name: cbshell-chart
  helm.sh/chart: cbshell-chart-1.0.1
  app.kubernetes.io/managed-by: Helm
  app.kubernetes.io/instance: cbshell-instance
  app.kubernetes.io/version: 1.0.1
  app.kubernetes.io/component: cloudshall
  app.kubernetes.io/part-of: cbshell-instance

service:
  externalPort: 22
  internalPort: 22
  name: cbshell-service
  type: LoadBalancer

users:
  pubkey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDDwoxj0pFnbrv5OYPjaNcdGaogFjQAmkTCedwB059fP5zjtn637eO3mHRzbZr/60PxNwnjmnC0XpxJUjA7kkhVDcRM15tSrC7sFC2dQzC6iXOknTAKGt3R1hwrgTOCKfdie3TJDWsd2zSkGHOookmvuj3dHopJATL4wTclGoG2LDKCinLgO/33fehdppNIACw6kWVBmhA3uKj3H8f3jPy+OM3wuZetVRosBqW8T2ptqEFBkynIEeevuBLkbmqFU0qHople78klCnXwSHodPRYMbmC8PbLaBt8k0Pj+L6OBS81+d2hKb9fv07ajBh7wLq7ub759IH6ag7Nm/Zn/28EdkxrjNh20qoq0g66MB26fjCpvxgLcteqiA1TaxvJo9oBYQyhwPympqanhQOWozUCDoaX4IHv64XE+AByduRjRAEu6wW25gfthabASujKO6uNvhswZ5P9GB+CVcqoiwHqKrhQEv0QppnuvuQNe2DOB5AXITjYvz5s9w/4QWTG+xTc= bob@yamato
