{{- if .Values.users.pubkey }}
apiVersion: v1
kind: Secret
metadata: 
  name: {{ .Chart.Name}}-secret
  labels:
    {{- range $key, $val := .Values.labels }}
    {{ $key }}: {{ $val | quote }}
    {{- end}}
type: Opaque
stringData:
  pubkey: {{ .Values.users.pubkey }}
{{- end }}